### ISSUE TITLE
Unknown ToolsVersion '12.0' on MonoDevelop on a Mac

### ISSUE THREAD

**Issue by digioak-zz** [Real-Serious-Games/RSG.UnityApp#1]
Following instructions at 

http://forums.xamarin.com/discussion/12066/unknown-toolsversion-12-0

seems to have solved the problem, just thought I'd document it here.

**Comment by digioak-zz** [comment]
Found your article on promises in Unity on codeproject.com and led me here.  Great project, thank you!

**Comment by ashleydavis** [comment]
Thanks for your feedback. If you want to get this project working on Xamarin please feel free to contribute.
